SELECT DM.DOCNUM, DM.VERSION, CO.CHECKOUTWHEN 
FROM MHGROUP.DOCMASTER DM
INNER JOIN MHGROUP.CHECKOUT CO
    ON DM.DOCNUM = CO.DOCNUM
    AND DM.VERSION = CO.VERSION
WHERE CHECKEDOUT = 'Y'
  AND YEAR(CO.CHECKOUTWHEN) < 2025;

 UPDATE MHGROUP.DOCMASTER
SET
    CHECKEDOUT = 'N',
    DOCINUSE = 'N'
  
    WHERE EXISTS (
    SELECT 1
    FROM MHGROUP.DOCMASTER DM
    WHERE DM.DOCNUM = MHGROUP.CHECKOUT.DOCNUM
      AND DM.VERSION = MHGROUP.CHECKOUT.VERSION
)
AND CHECKEDOUT = 'Y'
AND YEAR(CHECKOUTWHEN) < 2025;


DELETE FROM MHGROUP.CHECKOUT
WHERE DOCNUM IN (
    SELECT DM.DOCNUM 
FROM MHGROUP.DOCMASTER DM
INNER JOIN MHGROUP.CHECKOUT CO
    ON DM.DOCNUM = CO.DOCNUM
    AND DM.VERSION = CO.VERSION
WHERE CHECKEDOUT = 'Y'
  AND YEAR(CO.CHECKOUTWHEN) < 2025)
 

-- changes taken from https://stackoverflow.com/questions/17548751/how-to-write-a-sql-delete-statement-with-a-select-statement-in-the-where-clause